import type { Metadata } from "next";
import { Inter, Noto_Sans_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import NavBar from "@/components/cust/NavBar";

const inter = Inter({ subsets: ["latin"] });
const notoSansMono = Noto_Sans_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <body className={notoSansMono.className}> */}
        {/* <div className="border-4 border-blue-500">
        </div> */}
        <NavBar />
        <div>{children}</div>
      </body>
    </html>
  );
}
